Frontend/test
christian-japan-devs/VietcatholicJP pull request #18
Opened 2021-05-09 14:32 UTC by DangHoangGeo

@sandangel please

2021-05-09 14:57 UTC, sandangel requested changes
gitignore cái .dbdata , .DS_Store
revert mấy cái change .pnp.js, .yarn/cache/* , yarn.lock
copy change e đã code của backendside qua backend
bỏ backendside
muốn add eslint config react app thì tạo PR riêng

2021-05-09 14:59 UTC, DangHoangGeo commented
@sandangel em copy qua rồi

2021-05-09 14:59 UTC, sandangel commented
thế bỏ backendside đi @DangHoangGeo

2021-05-09 15:00 UTC, sandangel commented
e refresh lại page để xem comment mới nhất nha

2021-05-09 15:00 UTC, sandangel commented
sau khi e sửa xong thì e bấm request re-review

2021-05-09 15:53 UTC, DangHoangGeo reviewed
A review cái này nhé, do xoá cái appuser đi nên phần setting cũng phải bỏ luôn ạ.

2021-05-09 16:07 UTC, sandangel commented
@DangHoangGeo e revert cái change phần yarn đi

2021-05-09 16:07 UTC, sandangel commented
yarn.lock với .pnp.js nữa @DangHoangGeo

2021-05-09 16:10 UTC, sandangel commented
à cái workspace trong package.json e remove cái userapp là dc nha @DangHoangGeo

2021-05-09 16:11 UTC, sandangel commented on yarn.lock
> -"@babel/runtime@npm:^7.1.2, @babel/runtime@npm:^7.10.2, @babel/runtime@npm:^7.11.2, @babel/runtime@npm:^7.12.1, @babel/runtime@npm:^7.12.5, @babel/runtime@npm:^7.2.0, @babel/runtime@npm:^7.3.1, @babe
revert change file này

2021-05-09 16:11 UTC, sandangel commented on .pnp.js
> -        "npm:5.12.0"
revert change file này

2021-05-09 16:12 UTC, sandangel requested changes
merge branch fix trước zô main nha, xong merge main zô branch này

2021-05-09 16:23 UTC, sandangel commented
e merge  branch fix trước zô main nha, xong merge main zô branch này

2021-05-09 21:40 UTC, DangHoangGeo reviewed
@sandangel coi lai dum em nhe

2021-05-09 21:43 UTC, DangHoangGeo commented
Merging is blocked
Merging can be performed automatically once the requested changes are addressed.
@sandangel này nãy bị conflicted nên em sửa, giờ push lại nó đòi cái này mới cho merge.

2021-05-09 22:35 UTC, sandangel requested changes

2021-05-09 22:35 UTC, sandangel commented on yarn.lock
> +<<<<<<< HEAD
delete phần này đi e 😂😂

2021-05-10 09:24 UTC, DangHoangGeo commented on yarn.lock
> +<<<<<<< HEAD
@sandangel deleted rồi đó a

2021-05-10 10:13 UTC, sandangel reviewed
1 câu hỏi

2021-05-10 10:13 UTC, sandangel commented on backend/VietcatholicJP/wsgi/prod.py
> +#application = DjangoWhiteNoise(application)
thêm dòng nỳ làm chy á?

2021-05-10 10:42 UTC, DangHoangGeo commented on backend/VietcatholicJP/wsgi/prod.py
> +#application = DjangoWhiteNoise(application)
WhiteNoise allows your web app to serve its own static files, making it a self-contained unit that can be deployed anywhere without relying on nginx, Amazon S3 or any other external service. 
Tính dùng cho production a, mà em chưa thử bao giờ nên để tạm đó.

2021-05-10 10:45 UTC, sandangel approved these changes
E làm tốt lắm 😂😂😂

2021-05-10 10:47 UTC, DangHoangGeo commented
Ko biết khen thật hay đùa, Mà vẫn cảm ơn anh,

2021-05-10 10:48 UTC, merged